//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Use_Cases {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class FileSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static FileSettings defaultInstance = ((FileSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FileSettings())));
        
        public static FileSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../../../../Database/Admin.txt")]
        public string UserSettings {
            get {
                return ((string)(this["UserSettings"]));
            }
            set {
                this["UserSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../../../../Database/Logger.txt")]
        public string LoggerSettings {
            get {
                return ((string)(this["LoggerSettings"]));
            }
            set {
                this["LoggerSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../../../../Database/FinancialManagers.txt")]
        public string FinancialManagerSettings {
            get {
                return ((string)(this["FinancialManagerSettings"]));
            }
            set {
                this["FinancialManagerSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../../../../Database/Receptionists.txt")]
        public string ReceptionistSettings {
            get {
                return ((string)(this["ReceptionistSettings"]));
            }
            set {
                this["ReceptionistSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../../../../Database/SalesManagers.txt")]
        public string SalesManagerSettings {
            get {
                return ((string)(this["SalesManagerSettings"]));
            }
            set {
                this["SalesManagerSettings"] = value;
            }
        }
    }
}
